/*
 * SPDX-License-Identifier: Apache-2.0
 * This file is 100% AI-generated (Claude Code, Claude Opus 5.5).
 *
 * Generated by scripts/make-speech.py (voice Samantha): IMA ADPCM
 * clips at 8000 Hz in platform/assets/speech_words.bin. Do not edit.
 */

#ifndef AZ3166_SPEECH_WORDS_H
#define AZ3166_SPEECH_WORDS_H

#include <stdint.h>

#define SPEECH_RATE 8000u
#define SPEECH_WORD_COUNT 33u

typedef struct
{
    uint32_t offset;  /* bytes into speech_words.bin */
    uint32_t samples; /* 4-bit samples */
} speech_clip_t;

/* Word ids (crates/az3166-ecu/src/speech.rs uses the same order). */
enum
{
    SPEECH_ZERO = 0,
    SPEECH_ONE = 1,
    SPEECH_TWO = 2,
    SPEECH_THREE = 3,
    SPEECH_FOUR = 4,
    SPEECH_FIVE = 5,
    SPEECH_SIX = 6,
    SPEECH_SEVEN = 7,
    SPEECH_EIGHT = 8,
    SPEECH_NINE = 9,
    SPEECH_TEN = 10,
    SPEECH_ELEVEN = 11,
    SPEECH_TWELVE = 12,
    SPEECH_THIRTEEN = 13,
    SPEECH_FOURTEEN = 14,
    SPEECH_FIFTEEN = 15,
    SPEECH_SIXTEEN = 16,
    SPEECH_SEVENTEEN = 17,
    SPEECH_EIGHTEEN = 18,
    SPEECH_NINETEEN = 19,
    SPEECH_TWENTY = 20,
    SPEECH_THIRTY = 21,
    SPEECH_FORTY = 22,
    SPEECH_FIFTY = 23,
    SPEECH_SIXTY = 24,
    SPEECH_SEVENTY = 25,
    SPEECH_EIGHTY = 26,
    SPEECH_NINETY = 27,
    SPEECH_HUNDRED = 28,
    SPEECH_MINUS = 29,
    SPEECH_POINT = 30,
    SPEECH_DEGREES = 31,
    SPEECH_CELSIUS = 32,
};

static const speech_clip_t speech_clips[SPEECH_WORD_COUNT] = {
    {0u, 3777u}, /* ZERO */
    {1889u, 3362u}, /* ONE */
    {3570u, 2905u}, /* TWO */
    {5023u, 3458u}, /* THREE */
    {6752u, 2982u}, /* FOUR */
    {8243u, 3242u}, /* FIVE */
    {9864u, 2735u}, /* SIX */
    {11232u, 3410u}, /* SEVEN */
    {12937u, 2443u}, /* EIGHT */
    {14159u, 3730u}, /* NINE */
    {16024u, 3365u}, /* TEN */
    {17707u, 4009u}, /* ELEVEN */
    {19712u, 3532u}, /* TWELVE */
    {21478u, 4998u}, /* THIRTEEN */
    {23977u, 5774u}, /* FOURTEEN */
    {26864u, 5298u}, /* FIFTEEN */
    {29513u, 5548u}, /* SIXTEEN */
    {32287u, 6215u}, /* SEVENTEEN */
    {35395u, 5166u}, /* EIGHTEEN */
    {37978u, 5622u}, /* NINETEEN */
    {40789u, 3529u}, /* TWENTY */
    {42554u, 3425u}, /* THIRTY */
    {44267u, 3671u}, /* FORTY */
    {46103u, 4283u}, /* FIFTY */
    {48245u, 4350u}, /* SIXTY */
    {50420u, 4172u}, /* SEVENTY */
    {52506u, 3130u}, /* EIGHTY */
    {54071u, 4217u}, /* NINETY */
    {56180u, 3853u}, /* HUNDRED */
    {58107u, 3750u}, /* MINUS */
    {59982u, 3378u}, /* POINT */
    {61671u, 4030u}, /* DEGREES */
    {63686u, 4714u}, /* CELSIUS */
};

#endif
