/*
 * SPDX-License-Identifier: Apache-2.0
 * This file is 100% AI-generated (Claude Code, Claude Opus 5.5).
 */

//! Spoken temperature announcement: number to word clips. Word ids match
//! `platform/src/speech_words.h` (generated by `scripts/make-speech.py`).

pub const ZERO: u8 = 0; // ZERO..NINETEEN = 0..19
pub const TWENTY: u8 = 20; // TWENTY..NINETY = 20..27
pub const HUNDRED: u8 = 28;
pub const MINUS: u8 = 29;
pub const POINT: u8 = 30;
pub const DEGREES: u8 = 31;
pub const CELSIUS: u8 = 32;

pub const MAX_WORDS: usize = 12;

pub type Words = heapless::Vec<u8, MAX_WORDS>;

/// Words for 0..=999.
fn push_number(words: &mut Words, n: u32) {
    let hundreds = n / 100;
    let rest = n % 100;
    if hundreds > 0 {
        let _ = words.push(ZERO + hundreds as u8);
        let _ = words.push(HUNDRED);
        if rest == 0 {
            return;
        }
    }
    if rest < 20 {
        let _ = words.push(ZERO + rest as u8);
    } else {
        let _ = words.push(TWENTY + (rest / 10 - 2) as u8);
        if !rest.is_multiple_of(10) {
            let _ = words.push(ZERO + (rest % 10) as u8);
        }
    }
}

/// "minus twelve point five degrees celsius" for -125 (tenths of a degree).
pub fn temperature_words(tenths: i32) -> Words {
    let mut words = Words::new();
    if tenths < 0 {
        let _ = words.push(MINUS);
    }
    let abs = tenths.unsigned_abs().min(9999);
    push_number(&mut words, abs / 10);
    let _ = words.push(POINT);
    let _ = words.push(ZERO + (abs % 10) as u8);
    let _ = words.push(DEGREES);
    let _ = words.push(CELSIUS);
    words
}

#[cfg(test)]
mod tests {
    use super::*;

    const ONE: u8 = 1;
    const TWO: u8 = 2;
    const THREE: u8 = 3;
    const FIVE: u8 = 5;
    const TWELVE: u8 = 12;
    const THIRTY: u8 = 21;

    #[test]
    fn positive_with_tens_and_units() {
        assert_eq!(
            &temperature_words(235)[..],
            &[TWENTY, THREE, POINT, FIVE, DEGREES, CELSIUS]
        );
    }

    #[test]
    fn round_tens_and_teens() {
        assert_eq!(
            &temperature_words(300)[..],
            &[THIRTY, POINT, ZERO, DEGREES, CELSIUS]
        );
        assert_eq!(
            &temperature_words(121)[..],
            &[TWELVE, POINT, ONE, DEGREES, CELSIUS]
        );
    }

    #[test]
    fn negative_and_zero() {
        assert_eq!(
            &temperature_words(-125)[..],
            &[MINUS, TWELVE, POINT, FIVE, DEGREES, CELSIUS]
        );
        assert_eq!(
            &temperature_words(-3)[..],
            &[MINUS, ZERO, POINT, THREE, DEGREES, CELSIUS]
        );
        assert_eq!(
            &temperature_words(0)[..],
            &[ZERO, POINT, ZERO, DEGREES, CELSIUS]
        );
    }

    #[test]
    fn hundreds() {
        assert_eq!(
            &temperature_words(1052)[..],
            &[ONE, HUNDRED, FIVE, POINT, TWO, DEGREES, CELSIUS]
        );
    }
}
