#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# This file is 100% AI-generated (Claude Code, Claude Opus 5.5).
"""Generate the spoken words for the temperature announcement.

Renders each word with the macOS speech synthesizer (`say`) at 8 kHz, trims
leading/trailing silence, encodes it as IMA ADPCM (4 bit/sample) and writes

    platform/assets/speech_words.bin   all clips back to back
    platform/src/speech_words.h        word ids, offsets, sample counts

The outputs are committed, so building does not need macOS; run this only to
change the words or the voice:

    scripts/make-speech.py [--voice Samantha]
"""

import argparse
import subprocess
import tempfile
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RATE = 8000

# (identifier, spoken text). Ids are used by crates/az3166-ecu/src/speech.rs.
WORDS = [
    ("ZERO", "zero"), ("ONE", "one"), ("TWO", "two"), ("THREE", "three"),
    ("FOUR", "four"), ("FIVE", "five"), ("SIX", "six"), ("SEVEN", "seven"),
    ("EIGHT", "eight"), ("NINE", "nine"), ("TEN", "ten"), ("ELEVEN", "eleven"),
    ("TWELVE", "twelve"), ("THIRTEEN", "thirteen"), ("FOURTEEN", "fourteen"),
    ("FIFTEEN", "fifteen"), ("SIXTEEN", "sixteen"), ("SEVENTEEN", "seventeen"),
    ("EIGHTEEN", "eighteen"), ("NINETEEN", "nineteen"),
    ("TWENTY", "twenty"), ("THIRTY", "thirty"), ("FORTY", "forty"),
    ("FIFTY", "fifty"), ("SIXTY", "sixty"), ("SEVENTY", "seventy"),
    ("EIGHTY", "eighty"), ("NINETY", "ninety"), ("HUNDRED", "hundred"),
    ("MINUS", "minus"), ("POINT", "point"), ("DEGREES", "degrees"),
    ("CELSIUS", "celsius"),
]

SILENCE_THRESHOLD = 300  # 16-bit amplitude
GAP_SAMPLES = RATE * 40 // 1000  # keep 40 ms around each word

# IMA ADPCM tables
INDEX_TABLE = [-1, -1, -1, -1, 2, 4, 6, 8]
STEP_TABLE = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45,
    50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190, 209, 230,
    253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796, 876, 963,
    1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327,
    3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442,
    11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794,
    32767,
]


def adpcm_encode(samples: list[int]) -> bytes:
    """IMA ADPCM, predictor and index start at 0, low nibble first."""
    predictor, index = 0, 0
    nibbles = []
    for sample in samples:
        step = STEP_TABLE[index]
        diff = sample - predictor
        code = 0
        if diff < 0:
            code = 8
            diff = -diff
        delta = step >> 3
        if diff >= step:
            code |= 4
            diff -= step
            delta += step
        if diff >= step >> 1:
            code |= 2
            diff -= step >> 1
            delta += step >> 1
        if diff >= step >> 2:
            code |= 1
            delta += step >> 2
        predictor += -delta if code & 8 else delta
        predictor = max(-32768, min(32767, predictor))
        index = max(0, min(88, index + INDEX_TABLE[code & 7]))
        nibbles.append(code)
    if len(nibbles) % 2:
        nibbles.append(0)
    return bytes(nibbles[i] | (nibbles[i + 1] << 4) for i in range(0, len(nibbles), 2))


def render(text: str, voice: str, tmp: Path) -> list[int]:
    out = tmp / "word.wav"
    subprocess.run(["say", "-v", voice, "-o", str(out), f"--data-format=LEI16@{RATE}", text], check=True)
    with wave.open(str(out)) as w:
        assert (w.getnchannels(), w.getsampwidth(), w.getframerate()) == (1, 2, RATE)
        raw = w.readframes(w.getnframes())
    samples = [int.from_bytes(raw[i : i + 2], "little", signed=True) for i in range(0, len(raw), 2)]
    loud = [i for i, s in enumerate(samples) if abs(s) > SILENCE_THRESHOLD]
    if not loud:
        return samples
    start = max(0, loud[0] - GAP_SAMPLES)
    end = min(len(samples), loud[-1] + GAP_SAMPLES)
    return samples[start:end]


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--voice", default="Samantha")
    args = parser.parse_args()

    blob = bytearray()
    entries = []
    with tempfile.TemporaryDirectory() as tmp:
        for ident, text in WORDS:
            samples = render(text, args.voice, Path(tmp))
            entries.append((ident, len(blob), len(samples)))
            blob += adpcm_encode(samples)

    bin_path = ROOT / "platform" / "assets" / "speech_words.bin"
    bin_path.parent.mkdir(parents=True, exist_ok=True)
    bin_path.write_bytes(blob)

    lines = [
        "/*",
        " * SPDX-License-Identifier: Apache-2.0",
        " * This file is 100% AI-generated (Claude Code, Claude Opus 5.5).",
        " *",
        f" * Generated by scripts/make-speech.py (voice {args.voice}): IMA ADPCM",
        f" * clips at {RATE} Hz in platform/assets/speech_words.bin. Do not edit.",
        " */",
        "",
        "#ifndef AZ3166_SPEECH_WORDS_H",
        "#define AZ3166_SPEECH_WORDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define SPEECH_RATE {RATE}u",
        f"#define SPEECH_WORD_COUNT {len(entries)}u",
        "",
        "typedef struct",
        "{",
        "    uint32_t offset;  /* bytes into speech_words.bin */",
        "    uint32_t samples; /* 4-bit samples */",
        "} speech_clip_t;",
        "",
        "/* Word ids (crates/az3166-ecu/src/speech.rs uses the same order). */",
        "enum",
        "{",
    ]
    lines += [f"    SPEECH_{ident} = {i}," for i, (ident, _, _) in enumerate(entries)]
    lines += ["};", "", "static const speech_clip_t speech_clips[SPEECH_WORD_COUNT] = {"]
    lines += [f"    {{{offset}u, {samples}u}}, /* {ident} */" for ident, offset, samples in entries]
    lines += ["};", "", "#endif", ""]
    (ROOT / "platform" / "src" / "speech_words.h").write_text("\n".join(lines))

    seconds = sum(n for _, _, n in entries) / RATE
    print(f"{len(entries)} words, {seconds:.1f} s, {len(blob)} bytes -> {bin_path}")


if __name__ == "__main__":
    main()
